### ISSUE TITLE
"built-in"

### ISSUE THREAD

**Issue by orzFly** [RicterZ/genpAss#1]
https://github.com/RicterZ/genpAss/blob/master/src/rules/build_in.py

> built-in
> adjective
> forming an integral part of a structure: a worktop with a built-in cooker.
> • (of a characteristic) inherent; innate: the system has a built-in resistance to change.

**Comment by RicterZ** [comment]
thx _(:з」∠)_

**Comment by RicterZ** [comment]
900853e4b85ceaa46d1124b2e6fcc35e7a1944d3
